spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: DEBUG
    ru.t1.java.demo.controller.ClientController: DEBUG
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      groupDemo:
        group-id: t1-demo
        max.poll.records: 10
      groupAccount:
        group-id: t1-demo-account
        max.poll.records: 10
      groupTransaction:
        group-id: t1-demo-transaction
        max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      client_transactions: t1_demo_client_transactions
      demo_metrics: t1_demo_metrics
      demo_accounts: t1_demo_accounts
      demo_transactions: t1_demo_transactions
    listener:
      poll-timeout: 1000
